"""Generate the extension icons.

Committed as PNGs because that is what the browsers and the stores consume, but generated by
this script so the shapes stay reproducible rather than being a binary nobody can regenerate.

    python scripts/make-icons.py

Drawn at 8x and downsampled: PIL has no anti-aliased primitives, so supersampling is what keeps
the 16px toolbar icon from looking ragged. The mark is a cookie — the extension exports session
cookies, and a bitten disc with three chips stays readable when it is 16 pixels wide, which
almost nothing else does.
"""

from pathlib import Path

from PIL import Image, ImageDraw

SIZES = (16, 32, 48, 128)
SCALE = 8

# The portal's primary indigo, so the extension reads as part of the same product.
INDIGO = (79, 70, 229, 255)
DOUGH = (255, 255, 255, 255)
CHIP = (79, 70, 229, 255)

OUT = Path(__file__).resolve().parent.parent / "src" / "icons"


def render(size: int) -> Image.Image:
    px = size * SCALE
    img = Image.new("RGBA", (px, px), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    # Rounded-square tile. Full-bleed: a toolbar icon has no room for its own margin.
    radius = int(px * 0.22)
    d.rounded_rectangle([0, 0, px - 1, px - 1], radius=radius, fill=INDIGO)

    # The cookie, inset so the tile still reads as a tile at small sizes.
    pad = px * 0.18
    d.ellipse([pad, pad, px - pad, px - pad], fill=DOUGH)

    # The bite: a disc of tile colour overlapping the top-right edge.
    bite_r = px * 0.17
    bite_cx, bite_cy = px - pad - bite_r * 0.55, pad + bite_r * 0.55
    d.ellipse(
        [bite_cx - bite_r, bite_cy - bite_r, bite_cx + bite_r, bite_cy + bite_r],
        fill=INDIGO,
    )

    # Three chips, placed away from the bite so none of them is clipped by it.
    chip_r = px * 0.055
    for cx, cy in ((0.38, 0.42), (0.55, 0.62), (0.36, 0.68)):
        x, y = px * cx, px * cy
        d.ellipse([x - chip_r, y - chip_r, x + chip_r, y + chip_r], fill=CHIP)

    return img.resize((size, size), Image.LANCZOS)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for size in SIZES:
        path = OUT / f"icon-{size}.png"
        render(size).save(path, "PNG", optimize=True)
        print(f"wrote {path.relative_to(OUT.parent.parent)}")


if __name__ == "__main__":
    main()
